### PR TITLE
Add Kaushik's id_rsa.pub key.

### PR DESCRIPTION
**Pull request by roideuniverse**
Add Kaushik's public key

### CODE REVIEW

**Comment by slang800** [comment]
you can probably get rid of the "-work" part of the filename, since you don't have a "-personal" one in there.

**Comment by roideuniverse** [comment]
@slang800 Fair enough. Renamed it!

**Comment by slang800** [comment]
Thanks! Wanna squash it?

**Comment by roideuniverse** [comment]
@slang800 : Squashed!

**Comment by slang800** [comment]
perfect!

**Pull request merged**
